# Generated by Django 5.2.11 on 2026-02-24 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsot', '0044_attribute_depends_on'),
        ('nsot', '0044_attribute_inheritable'),
    ]

    operations = [
    ]
