# Generated by Django 5.2.11 on 2026-02-25 00:02

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsot', '0045_attribute_inheritable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='resource_name',
            field=models.CharField(choices=[('Network', 'Network'), ('Device', 'Device'), ('Interface', 'Interface'), ('Circuit', 'Circuit'), ('Protocol', 'Protocol'), ('AutonomousSystem', 'AutonomousSystem')], db_index=True, help_text='The name of the Resource to which this Attribute is bound.', max_length=20, verbose_name='Resource Name'),
        ),
        migrations.AlterField(
            model_name='change',
            name='resource_name',
            field=models.CharField(choices=[('Site', 'Site'), ('Network', 'Network'), ('Attribute', 'Attribute'), ('Device', 'Device'), ('Interface', 'Interface'), ('Circuit', 'Circuit'), ('Protocol', 'Protocol'), ('ProtocolType', 'ProtocolType'), ('AutonomousSystem', 'AutonomousSystem')], db_index=True, help_text='The name of the Resource for this Change.', max_length=20, verbose_name='Resource Type'),
        ),
        migrations.AlterField(
            model_name='value',
            name='resource_name',
            field=models.CharField(choices=[('Network', 'Network'), ('Device', 'Device'), ('Interface', 'Interface'), ('Circuit', 'Circuit'), ('Protocol', 'Protocol'), ('AutonomousSystem', 'AutonomousSystem')], db_index=True, help_text='The name of the Resource type to which the Value is bound.', max_length=20, verbose_name='Resource Type'),
        ),
        migrations.CreateModel(
            name='AutonomousSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_attributes_cache', django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='Local cache of attributes. (Internal use only)')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, default=None, help_text='Optional expiration timestamp. Resources with expires_at in the past are considered expired.', null=True)),
                ('number', models.PositiveBigIntegerField(db_index=True, help_text='The Autonomous System Number (ASN). Valid range: 1-4294967294.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4294967294)])),
                ('description', models.CharField(blank=True, default='', help_text='A brief description of this Autonomous System.', max_length=255)),
                ('site', models.ForeignKey(help_text='Unique ID of the Site this Autonomous System is under.', on_delete=django.db.models.deletion.PROTECT, related_name='autonomous_systems', to='nsot.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Autonomous System',
                'verbose_name_plural': 'Autonomous Systems',
                'unique_together': {('site', 'number')},
            },
        ),
        migrations.AddField(
            model_name='protocol',
            name='autonomous_system',
            field=models.ForeignKey(blank=True, help_text='The Autonomous System associated with this protocol instance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protocols', to='nsot.autonomoussystem'),
        ),
    ]
